---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-2.0.3
  - EMBER_TRY_SCENARIO=ember-2.1.2
  - EMBER_TRY_SCENARIO=ember-2.2.2
  - EMBER_TRY_SCENARIO=ember-2.3.1
  - EMBER_TRY_SCENARIO=ember-2.4.6-LTS
  - EMBER_TRY_SCENARIO=ember-2.5.1
  - EMBER_TRY_SCENARIO=ember-2.6.2

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try $EMBER_TRY_SCENARIO test --skip-cleanup

addons:
  code_climate:
    repo_token: 8eea650d4493e34429bf149a5b9d68f78963b56410568902bf9d52eed54c8cc5

after_script:
  - codeclimate < lcov.dat
